
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tipo_dato = 27;
  public static final int LPARENT = 3;
  public static final int RPARENT = 5;
  public static final int DIVIDE = 15;
  public static final int corcheteI = 25;
  public static final int EQUALS = 7;
  public static final int SI = 17;
  public static final int corcheteD = 26;
  public static final int write = 22;
  public static final int coma = 28;
  public static final int FIN = 35;
  public static final int MINUS = 14;
  public static final int read = 21;
  public static final int ENDSI = 18;
  public static final int PLUS = 12;
  public static final int ASSIGN = 6;
  public static final int ID = 2;
  public static final int ENDWHILE = 20;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int DIF = 4;
  public static final int Salto = 33;
  public static final int MENOR = 11;
  public static final int MOD = 16;
  public static final int llaveI = 23;
  public static final int vacio = 32;
  public static final int Num = 31;
  public static final int MAYOR = 10;
  public static final int llaveD = 24;
  public static final int TIMES = 13;
  public static final int WHILE = 19;
  public static final int MAYOR_IGUAL = 8;
  public static final int salto = 29;
  public static final int INICIO = 34;
  public static final int MENOR_IGUAL = 9;
  public static final int cadena = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "LPARENT",
  "DIF",
  "RPARENT",
  "ASSIGN",
  "EQUALS",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "MAYOR",
  "MENOR",
  "PLUS",
  "TIMES",
  "MINUS",
  "DIVIDE",
  "MOD",
  "SI",
  "ENDSI",
  "WHILE",
  "ENDWHILE",
  "read",
  "write",
  "llaveI",
  "llaveD",
  "corcheteI",
  "corcheteD",
  "tipo_dato",
  "coma",
  "salto",
  "cadena",
  "Num",
  "vacio",
  "Salto",
  "INICIO",
  "FIN"
  };
}

